# Plik konfiguracyjny Codemagic dla aplikacji iOS "bartek" - Wynajem Samochodów
# Autor: Jakub Nowosad
# Data: 13.06.2025

workflows:
  # Workflow deweloperski - uproszczony build bez podpisywania (idealny dla studentów)
  ios-development:
    name: iOS Development Build
    instance_type: mac_mini_m1
    max_build_duration: 60    environment:
      vars:
        XCODE_PROJECT: "bartek.xcodeproj"
        XCODE_SCHEME: "bartek"
        BUNDLE_ID: "com.jacooo13.bartek"
      xcode: 15.2
    
    scripts:
      - name: Debug project structure
        script: |
          echo "=== Checking project structure ==="
          ls -la "$CM_BUILD_DIR/"
          echo "=== Checking xcodeproj content ==="
          ls -la "$CM_BUILD_DIR/bartek.xcodeproj/"
          echo "=== Checking project.pbxproj ==="
          head -20 "$CM_BUILD_DIR/$XCODE_PROJECT/project.pbxproj"
          echo "=== Checking objectVersion ==="
          grep "objectVersion" "$CM_BUILD_DIR/$XCODE_PROJECT/project.pbxproj"
          echo "=== Trying to validate project ==="
          xcodebuild -project "$CM_BUILD_DIR/$XCODE_PROJECT" -list || echo "Project validation failed"
      
      - name: Fix project compatibility (if needed)
        script: |
          echo "=== Attempting to fix project compatibility ==="
          # Sprawdź czy projekt ma objectVersion = 77 (Xcode 16)
          if grep -q "objectVersion = 77" "$CM_BUILD_DIR/$XCODE_PROJECT/project.pbxproj"; then
            echo "Found Xcode 16 project format, attempting to downgrade..."
            # Zamień objectVersion na kompatybilną z Xcode 15
            sed -i.bak 's/objectVersion = 77;/objectVersion = 56;/g' "$CM_BUILD_DIR/$XCODE_PROJECT/project.pbxproj"
            echo "Project format downgraded to Xcode 15 compatibility"
          else
            echo "Project format appears compatible"
          fi
      
      - name: Set up keychain for code signing (optional, if needed)
        script: |
          # Keychains are not persisted for free tier, set up fresh each time if manual signing is used.
          # For automatic signing or builds without distribution, this might not be needed.
          echo "Skipping keychain setup for basic build"
        - name: Build project for iOS Simulator (with fallback)
        script: |
          set -eo pipefail # Exit on error
          
          echo "=== Trying primary build method ==="
          if xcodebuild build \
            -project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID"; then
            echo "Primary build succeeded"
          else
            echo "Primary build failed, trying alternative approach..."
            
            # Próba 1: Użyj domyślnego scheme
            echo "=== Trying with default scheme ==="
            xcodebuild build \
              -project "$CM_BUILD_DIR/$XCODE_PROJECT" \
              -sdk iphonesimulator \
              -configuration Debug \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" || \
            
            # Próba 2: Bez specyfikacji scheme
            echo "=== Trying without scheme specification ==="
            xcodebuild \
              -project "$CM_BUILD_DIR/$XCODE_PROJECT" \
              -sdk iphonesimulator \
              -configuration Debug \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              build
          fi
      
      - name: Build project for iOS Device (without signing)
        script: |
          set -eo pipefail # Exit on error

          xcodebuild build \
            -project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID"
    
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Debug-iphonesimulator/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Release-iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - jakub.nowosad@student.example.com  # Zmień na swój email
        notify:
          success: true
          failure: true

  # Workflow testowy - uruchamianie testów jednostkowych
  ios-testing:
    name: iOS Unit Tests
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      vars:
        XCODE_PROJECT: "bartek.xcodeproj"
        XCODE_SCHEME: "bartek"
      xcode: 15.2
    scripts:
      - name: Run unit tests
        script: |
          set -eo pipefail # Exit on error
          
          xcodebuild test \
            -project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
    
    artifacts:
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - jakub.nowosad@student.example.com
        notify:
          success: false  # Nie wysyłaj emaila przy sukcesie testów
          failure: true   # Tylko przy niepowodzeniu
